#!/usr/bin/env node
/**
 * Build and deploy this app to Cloudflare Workers.
 *
 * Usage:
 *   pnpm cf-deploy --deploy-env <name> --primitive-env <name> [--check] [-- wrangler args...]
 *
 * TWO INDEPENDENT AXES, neither of which defaults:
 *
 *   --deploy-env <name>     WHICH FRONT END. The Vite mode (`--mode <name>`,
 *                           so `.env.<name>` applies) and the Wrangler
 *                           environment (`[env.<name>]` in wrangler.toml).
 *
 *   --primitive-env <name>  WHICH BACKEND / APP. A key in
 *                           `.primitive/config.json`, supplying apiUrl,
 *                           appId and appName.
 *
 * They cross in practice — a production front end against the alpha backend, a
 * customer whose dev and prod builds both hit primitiveapi.com with different
 * app IDs — so neither is inferred from the other, and omitting either is an
 * error. Say "deploy environment" or "Primitive environment"; a bare
 * "environment" is ambiguous here. An app whose `.env.<mode>` carries values
 * coupled to one backend can pin the pair anyway: declare
 * `VITE_EXPECTED_PRIMITIVE_ENV=<name>` there and a mismatched `--primitive-env`
 * stops this script before it plans or builds anything.
 *
 * Examples:
 *   pnpm cf-deploy --deploy-env production --primitive-env prod
 *   pnpm cf-deploy --deploy-env production --primitive-env alpha
 *   pnpm cf-deploy --deploy-env production --primitive-env prod --check
 *   pnpm cf-deploy --deploy-env production --primitive-env prod -- --dry-run
 *
 * `.primitive/config.json` is the ONLY place the backend URL and app ID are
 * typed. This script reads them from there and passes them to the worker as
 * `--var APP_ID` / `--var API_ORIGIN`; the build gets `PRIMITIVE_ENV` so the
 * `primitiveEnv()` Vite plugin resolves the same environment. An identity key
 * (`VITE_APP_ID`, `VITE_API_URL`, `VITE_WS_URL`, `VITE_APP_NAME`) in a `.env`
 * file or the shell is a hard error rather than a silent second source.
 *
 * Node builtins only, and every spawn is an argv array with `shell: false`.
 */

import { spawn } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT_DIR = resolve(__dirname, "..");

/** Schema version of `.primitive/config.json` this script understands. */
const CONFIG_VERSION = 1;

/**
 * The association document Apple fetches, generated per deploy (#3081).
 *
 * An app has one iOS bundle id per environment, so a single committed file can
 * only ever be right for one of them — and a document naming the wrong app
 * PARSES, so Apple accepts it, caches it, and universal links and passkeys both
 * fail with nothing to read. This script already resolves which environment is
 * being deployed, and it runs before the build copies `public/` into `dist/`,
 * so it is the one place that can write the right document.
 */
const AASA_RELATIVE = "public/.well-known/apple-app-site-association";
/** The developer's explicit "this document is mine" opt-in, committed beside it. */
const AASA_SENTINEL_RELATIVE = `${AASA_RELATIVE}.hand-authored`;
/** What marks a document as this script's to overwrite or delete. */
const AASA_MARKER = "Generated by scripts/deploy.mjs";
/** The path the generated `applinks` component claims, and the web app serves. */
const CALLBACK_PATH = "/oauth/callback";
/** The callback the build may point somewhere else — checked against the above. */
const REDIRECT_URI_KEY = "VITE_OAUTH_REDIRECT_URI";

/**
 * `<Application Identifier Prefix>.<bundle id>` — the prefix is ten
 * alphanumerics, usually the Team ID (a legacy app's can differ; TN2311).
 * Duplicated from the CLI's `ios-app-id.ts` on purpose: this script is
 * self-contained, node builtins only, as the identity rules here already are.
 */
const IOS_APP_ID = /^[A-Z0-9]{10}\.[A-Za-z0-9.-]+$/;

/** The only hosts an http origin may have, as `web-url.ts` has it. */
const LOOPBACK_HOSTS = new Set(["localhost", "127.0.0.1"]);

/**
 * The CLI's `iosAppId` and `webUrl` rules, restated for the two readers below.
 *
 * `.primitive/config.json` is committed and hand-edited — the README says so
 * for an environment that already exists — so a value that never went through
 * `primitive env add` is the normal case, not the exotic one. This script is
 * the LAST check before a document reaches Apple, and it is the only one on
 * that path, so anything `cli/src/lib/ios-app-id.ts` or `web-url.ts` would
 * refuse to write has to stop the deploy too. `ABCDE12345.BUNDLEID` parses as
 * a document naming an app nobody ships; a `webUrl` with a path is the origin
 * the resolver core reads as no web counterpart at all. The parity is pinned
 * by `cli/tests/unit/vue-cf-deploy-aasa-3081.test.ts`.
 *
 * Each returns the specific problem, or null when the value is good.
 */
function iosAppIdProblem(value) {
  if (typeof value !== "string" || !value.trim()) return "it must be a non-empty string";
  const trimmed = value.trim();
  const dot = trimmed.indexOf(".");
  if (dot === -1) return "there is no dot between the prefix and the bundle id";
  const prefix = trimmed.slice(0, dot);
  const bundleId = trimmed.slice(dot + 1);
  if (prefix === "TEAMID" || bundleId === "BUNDLEID") {
    return 'it is still the "TEAMID.BUNDLEID" placeholder';
  }
  if (!/^[A-Z0-9]{10}$/.test(prefix)) {
    return `"${prefix}" is not a 10-character Application Identifier Prefix`;
  }
  if (!bundleId) return "there is no bundle id after the prefix";
  if (!IOS_APP_ID.test(trimmed)) {
    return "the bundle id may only contain letters, digits, dots and dashes";
  }
  return null;
}

function webUrlProblem(value) {
  if (typeof value !== "string" || !value.trim()) return "it must be a non-empty string";
  let url;
  try {
    url = new URL(value.trim());
  } catch {
    return "it is not an absolute URL";
  }
  if (url.protocol !== "https:" && url.protocol !== "http:") return "it must be http(s)";
  if (url.protocol === "http:" && !LOOPBACK_HOSTS.has(url.hostname)) {
    return "it must use https outside localhost — the server refuses a non-loopback http redirect URI";
  }
  if (url.username || url.password) return "it must not carry credentials";
  if (url.pathname !== "/" && url.pathname !== "") {
    return "it must be an origin with no path — the web app serves its callback on its own origin";
  }
  if (url.search) return "it must not carry a query";
  if (url.hash) return "it must not carry a fragment";
  return null;
}

/** Keys the `primitiveEnv()` plugin owns. Authoring one here is the old way. */
const IDENTITY_KEYS = ["VITE_APP_ID", "VITE_API_URL", "VITE_WS_URL", "VITE_APP_NAME"];

/** Opt-in: the Primitive environment a deploy environment is meant to pair with. */
const EXPECTED_ENV_KEY = "VITE_EXPECTED_PRIMITIVE_ENV";

const USAGE = `Usage: pnpm cf-deploy --deploy-env <name> --primitive-env <name> [--check] [-- wrangler args...]

  --deploy-env <name>     Which front end: the Vite mode and the wrangler.toml
                          [env.<name>] section. e.g. production
  --primitive-env <name>  Which backend/app: an environment in
                          .primitive/config.json. e.g. prod, alpha
  --check                 Print the resolved pair and the exact commands, then exit.

Both are required — neither is inferred from the other.

  pnpm cf-deploy --deploy-env production --primitive-env prod`;

function fail(...lines) {
  for (const line of lines) console.error(`[deploy] ${line}`);
  process.exit(1);
}

function parseArgs(argv) {
  const parsed = {
    deployEnv: null,
    primitiveEnv: null,
    check: false,
    positional: null,
    passthrough: [],
  };

  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === "--") {
      parsed.passthrough.push(...argv.slice(i + 1));
      break;
    }
    if (arg === "--deploy-env") {
      parsed.deployEnv = argv[++i] ?? null;
    } else if (arg.startsWith("--deploy-env=")) {
      parsed.deployEnv = arg.slice("--deploy-env=".length);
    } else if (arg === "--primitive-env") {
      parsed.primitiveEnv = argv[++i] ?? null;
    } else if (arg.startsWith("--primitive-env=")) {
      parsed.primitiveEnv = arg.slice("--primitive-env=".length);
    } else if (arg === "--check" || arg === "--dry-run-plan") {
      parsed.check = true;
    } else if (!arg.startsWith("-") && parsed.positional === null) {
      parsed.positional = arg;
    } else {
      // Anything else before `--` is an unknown flag. There is deliberately no
      // escape hatch here (notably none for the identity check below), so an
      // unrecognized flag is a mistake worth naming.
      fail(`Unknown option: ${arg}`, "", USAGE);
    }
  }

  return parsed;
}

/** Finds `.primitive/config.json`, honoring the PRIMITIVE_PROJECT_CONFIG override. */
function findProjectConfigPath() {
  const override = process.env.PRIMITIVE_PROJECT_CONFIG;
  if (override) {
    const forced = resolve(override);
    return existsSync(forced) ? forced : null;
  }
  let current = ROOT_DIR;
  for (;;) {
    const candidate = join(current, ".primitive", "config.json");
    if (existsSync(candidate)) return candidate;
    const parent = dirname(current);
    if (parent === current) return null;
    current = parent;
  }
}

/** Reads the environment identity for `name`, failing loudly on anything odd. */
function readPrimitiveEnvironment(name) {
  const configPath = findProjectConfigPath();
  if (!configPath) {
    fail(
      "No .primitive/config.json found for this project.",
      "It is the single source of truth for the backend URL and app ID.",
      "Run 'primitive init' to create one, or 'primitive env add <name> --api-url ... --app-id ...'.",
    );
  }

  let config;
  try {
    config = JSON.parse(readFileSync(configPath, "utf-8"));
  } catch (err) {
    fail(`Could not parse ${configPath}: ${err.message}`);
  }

  if (config?.version !== CONFIG_VERSION) {
    fail(
      `${configPath} has version ${config?.version}, but this script understands version ${CONFIG_VERSION}.`,
      "Upgrade the Primitive CLI and this template together.",
    );
  }
  if (!config.environments || typeof config.environments !== "object") {
    fail(`${configPath} has no "environments" object.`);
  }

  const entry = config.environments[name];
  if (!entry) {
    const available = Object.keys(config.environments).join(", ") || "(none)";
    fail(
      `Primitive environment "${name}" is not defined in ${configPath}.`,
      `Available: ${available}`,
    );
  }
  if (typeof entry.apiUrl !== "string" || !entry.apiUrl) {
    fail(`Primitive environment "${name}" has no "apiUrl" in ${configPath}.`);
  }
  // Typed, not merely present: the schema says these are strings, and every
  // reader treats a non-string or blank value as naming no app at all. One
  // would otherwise reach wrangler as `--var APP_ID:[object Object]`.
  //
  // The remedy is the canonical one (#3152): NOT `primitive env add <name>`,
  // which refuses an environment name that already exists, and no command that
  // has to run inside a project whose config the CLI itself now rejects.
  if (typeof entry.appId !== "string" || !entry.appId.trim()) {
    fail(
      `Primitive environment "${name}" in ${configPath} has no "appId".`,
      `Every environment names exactly one app — add "appId": "<app-id>" to that environment in .primitive/config.json.`,
      `Find the app id in the Primitive admin UI, with 'primitive apps list' run from a directory outside this project,`,
      `or as the residual "currentAppId" in .primitive/credentials.json if this environment was ever pointed at an app`,
      `by the retired per-machine app selection.`,
    );
  }

  // The iOS half of this environment (#3081). Both fields or neither: the
  // association document naming the app is served by the web app, so an
  // `iosAppId` with no `webUrl` names an app for a domain nothing here knows.
  let iosAppId;
  let webUrl;
  if (entry.iosAppId !== undefined) {
    const appIdProblem = iosAppIdProblem(entry.iosAppId);
    if (appIdProblem) {
      fail(
        `Primitive environment "${name}" has an invalid "iosAppId" in ${configPath}: ${JSON.stringify(entry.iosAppId)}`,
        `(${appIdProblem}.)`,
        "It must be <Application Identifier Prefix>.<bundle id> — the prefix is 10 characters,",
        "usually your Team ID (verify it against the signed app's application-identifier",
        "entitlement). e.g. ABCDE12345.com.example.app",
        `A wrong value here still parses as a document, so Apple caches it and universal links`,
        "and passkeys fail silently — which is why this is an error and not a warning.",
      );
    }
    iosAppId = entry.iosAppId.trim();
    if (entry.webUrl === undefined || (typeof entry.webUrl === "string" && !entry.webUrl.trim())) {
      fail(
        `Primitive environment "${name}" sets "iosAppId" but no "webUrl" in ${configPath}.`,
        `The apple-app-site-association document naming ${iosAppId} is served by this`,
        "environment's web app, so the deploy has to know its origin. Add",
        `"webUrl": "https://<your-domain>" to that environment — or drop "iosAppId" if it has`,
        "no iOS client.",
      );
    }
    const webProblem = webUrlProblem(entry.webUrl);
    if (webProblem) {
      fail(
        `Primitive environment "${name}" has an invalid "webUrl" in ${configPath}: ${JSON.stringify(entry.webUrl)}`,
        `(${webProblem}.)`,
        "It must be a bare origin — no path, query, fragment or credentials —",
        "e.g. https://app.example.com (or http://localhost:5173 in dev).",
        `That origin is where the document naming ${iosAppId} is served and what the emailed`,
        "sign-in link is built from; a value the CLI would not store is one the iOS client",
        "reads as no web counterpart at all.",
      );
    }
    webUrl = new URL(entry.webUrl.trim()).origin;
  }

  return {
    name,
    apiUrl: entry.apiUrl.replace(/\/$/, ""),
    appId: entry.appId.trim(),
    appName: typeof entry.appName === "string" ? entry.appName : undefined,
    iosAppId,
    webUrl,
    configPath,
  };
}

/**
 * Minimal `.env` reader — same rules the primitiveEnv() plugin applies, which
 * are Vite's own: a quoted value ends at its closing quote (a `#` inside it is
 * content, and the rest of the line is a comment), an unquoted one ends at the
 * first inline comment. The deploy and the build it launches must never read a
 * `.env` line differently.
 */
function parseEnvFile(path) {
  if (!existsSync(path)) return {};
  const out = {};
  for (const line of readFileSync(path, "utf-8").split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const match = trimmed.match(/^(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/);
    if (!match) continue;
    const value = match[2].trim();
    const quote = value[0];
    const close =
      quote === '"' || quote === "'" || quote === "`" ? value.indexOf(quote, 1) : -1;
    out[match[1]] = close === -1 ? value.replace(/\s+#.*$/, "").trim() : value.slice(1, close);
  }
  return out;
}

/**
 * The value the BUILD would see for `key`, by Vite's precedence: a non-empty
 * ambient value wins outright, otherwise `.env`, `.env.local`, `.env.<mode>`,
 * `.env.<mode>.local` in that order with a later file winning — and an empty
 * value in a later file cancelling the one below it rather than inheriting it.
 *
 * Read from the project root, as the rest of this script is: the template never
 * sets Vite's `envDir`.
 */
function resolveBuildEnvValue(key, deployEnv) {
  const ambient = process.env[key];
  if (ambient !== undefined && ambient !== "") {
    return { value: ambient, where: "the process environment" };
  }
  let found = { value: null, where: null };
  for (const file of [".env", ".env.local", `.env.${deployEnv}`, `.env.${deployEnv}.local`]) {
    const value = parseEnvFile(join(ROOT_DIR, file))[key];
    if (value !== undefined) found = { value, where: file };
  }
  return found;
}

/**
 * A deploy is strict about identity: the build must take it from
 * `.primitive/config.json`, and the worker vars below come from the same
 * place. An identity key anywhere the build would see it means the two could
 * disagree, so it stops the deploy. There is no override flag — remove the
 * key. (This is also the migration step for an app scaffolded by an older CLI,
 * which appended these keys to `.env`.)
 */
function assertNoIdentityOverrides(deployEnv) {
  const found = [];

  for (const key of IDENTITY_KEYS) {
    if (process.env[key] !== undefined && process.env[key] !== "") {
      found.push({ key, where: "the process environment" });
    }
  }

  for (const file of [".env", ".env.local", `.env.${deployEnv}`, `.env.${deployEnv}.local`]) {
    const vars = parseEnvFile(join(ROOT_DIR, file));
    for (const key of IDENTITY_KEYS) {
      if (vars[key] !== undefined) found.push({ key, where: file });
    }
  }

  if (found.length === 0) return;

  fail(
    "Identity keys must not be set for a deploy — they would compete with .primitive/config.json:",
    ...found.map(({ key, where }) => `  ${key} (in ${where})`),
    "",
    "Remove them. The backend URL and app ID are typed once, in .primitive/config.json,",
    "and reach the build through the primitiveEnv() Vite plugin. If this app was",
    "scaffolded by an older CLI, deleting these lines from your .env files is the",
    "whole migration.",
  );
}

/**
 * The two axes cross on purpose — but an app whose `.env.<mode>` carries
 * values coupled to one backend can pin the pair by declaring
 * `VITE_EXPECTED_PRIMITIVE_ENV` in that file. The `primitiveEnv()` plugin
 * enforces the same declaration inside the build; this pre-flight runs first
 * because `--check` never builds, and because a `[deploy]` line is a better
 * answer than a stack trace from a build child process.
 *
 * Read from the project root, as the rest of this script is: the template
 * never sets Vite's `envDir`, and a cross-wired real deploy under a custom one
 * still fails inside the build.
 */
function assertPairing(deployEnv, primitiveEnv) {
  const { value: declared, where } = resolveBuildEnvValue(EXPECTED_ENV_KEY, deployEnv);

  if (!declared || declared === primitiveEnv) return;

  fail(
    `Wrong pair: deploy environment "${deployEnv}" declares ${EXPECTED_ENV_KEY}="${declared}"`,
    `(in ${where}), but --primitive-env is "${primitiveEnv}".`,
    "",
    `Deploy the pair you meant: --deploy-env ${deployEnv} --primitive-env ${declared}`,
    `— or change/remove the ${EXPECTED_ENV_KEY} declaration in ${where}.`,
  );
}

/**
 * The document Apple fetches, for ONE environment's app.
 *
 * The top level carries only Apple's documented service keys — a nonstandard
 * key risks rejection by a strict parser, and a rejected document is cached
 * exactly like an accepted one. So the ownership marker and the environment
 * name live in the documented component `comment` field, where `curl` on a
 * domain shows which environment's deploy wrote what it is serving.
 */
function renderAssociationDocument(env) {
  const comment =
    `${AASA_MARKER} from .primitive/config.json ("${env.name}") — do not edit; ` +
    `see public/.well-known/README.md. The query constraint claims only the emailed sign-in link.`;
  return (
    JSON.stringify(
      {
        applinks: {
          details: [
            {
              appIDs: [env.iosAppId],
              components: [{ "/": CALLBACK_PATH, "?": { magic_token: "*" }, comment }],
            },
          ],
        },
        webcredentials: { apps: [env.iosAppId] },
      },
      null,
      2,
    ) + "\n"
  );
}

/**
 * The link the web app emails must be the one the generated document claims.
 *
 * The template supports an absolute `VITE_OAUTH_REDIRECT_URI` on a fixed host
 * different from where the app is served, so a path-only check would pass a
 * redirect whose origin serves no association document at all: the deploy
 * succeeds and every emailed link opens in the browser. Origin AND path.
 */
function assertCallbackMatchesDocument(env, deployEnv) {
  const { value, where } = resolveBuildEnvValue(REDIRECT_URI_KEY, deployEnv);
  if (!value) return;

  const remedies = [
    "",
    `Align the two: point ${REDIRECT_URI_KEY} at ${env.webUrl}${CALLBACK_PATH} — or drop it, since`,
    "the web app derives that path from its own origin. If the callback really does live",
    `elsewhere, take manual ownership of the document instead (${AASA_SENTINEL_RELATIVE};`,
    "see public/.well-known/README.md).",
  ];

  let url = null;
  if (/^[a-zA-Z][a-zA-Z0-9+.-]*:/.test(value)) {
    try {
      url = new URL(value);
    } catch {
      fail(`${REDIRECT_URI_KEY} is "${value}" (in ${where}), which is not a URL.`, ...remedies);
    }
  }

  if (!url) {
    if (value === CALLBACK_PATH) return;
    fail(
      `${REDIRECT_URI_KEY} is "${value}" (in ${where}), but the apple-app-site-association this`,
      `deploy generates for "${env.name}" claims "${CALLBACK_PATH}".`,
      "iOS matches the claim against the link's path, so the app would never open.",
      ...remedies,
    );
  }

  if (url.pathname === CALLBACK_PATH && url.origin === env.webUrl) return;
  fail(
    `${REDIRECT_URI_KEY} is "${value}" (in ${where}), but the apple-app-site-association this`,
    `deploy generates for "${env.name}" is served by ${env.webUrl} and claims ${CALLBACK_PATH}.`,
    "A link on another origin or path is not claimed by the app: the deploy succeeds and every",
    "emailed link opens in the browser instead.",
    ...remedies,
  );
}

/**
 * What this deploy will do about the association document — decided before the
 * build, and before `--check` returns, so every refusal below fails a `--check`
 * run too.
 *
 * The dangerous state is a file this script did not write. The pre-#3081 flow
 * told developers to rename the shipped `.example` and fill in ONE app id, so
 * such a file exists in real apps and names whichever environment was typed
 * into it. Passing it through silently is the original bug, so a hand-authored
 * document is legitimate only beside a committed sentinel that says so.
 */
function planAssociationDocument(env, deployEnv) {
  const documentPath = join(ROOT_DIR, AASA_RELATIVE);
  const present = existsSync(documentPath);
  const scriptOwned = present && readFileSync(documentPath, "utf-8").includes(AASA_MARKER);
  const claimed = existsSync(join(ROOT_DIR, AASA_SENTINEL_RELATIVE));

  if (env.iosAppId) {
    if (present && !scriptOwned) {
      fail(
        `Two sources want to define ${AASA_RELATIVE}:`,
        `  - Primitive environment "${env.name}" sets "iosAppId": ${env.iosAppId} (${env.configPath})`,
        `  - ${AASA_RELATIVE} exists and this script did not write it (no "${AASA_MARKER}" marker)`,
        "",
        "Generating over a hand-authored document would silently discard it, so nothing was",
        `written. Delete ${AASA_RELATIVE} to let each deploy generate the document for the`,
        `environment it deploys — or remove "iosAppId" from that environment and keep the file,`,
        `with ${AASA_SENTINEL_RELATIVE} beside it to own it by hand.`,
      );
    }
    assertCallbackMatchesDocument(env, deployEnv);
    return {
      action: "write",
      path: documentPath,
      body: renderAssociationDocument(env),
      describe: `write ${AASA_RELATIVE} naming ${env.iosAppId} (Primitive environment "${env.name}")`,
    };
  }

  if (scriptOwned) {
    return {
      action: "delete",
      path: documentPath,
      describe:
        `Primitive environment "${env.name}" has no "iosAppId", so delete the previously ` +
        `generated ${AASA_RELATIVE} — this deploy serves NO association document rather than ` +
        `one naming another environment's app. If "${env.name}" does have an iOS client, set ` +
        `"iosAppId" on it in ${env.configPath} (a CLI older than #3081 drops that field whenever ` +
        `it rewrites the config).`,
    };
  }

  if (present && !claimed) {
    fail(
      `${AASA_RELATIVE} was not written by this script (no "${AASA_MARKER}" marker), and`,
      `Primitive environment "${env.name}" has no "iosAppId" to generate one from.`,
      "A document naming another environment's app parses, so Apple accepts and caches it, and",
      "universal links and passkeys then fail with no error to read. Refusing to ship it blind.",
      "",
      "Pick one:",
      `  - set "iosAppId" on environment "${env.name}" in ${env.configPath}, beside its "webUrl",`,
      "    and every deploy generates the document for the environment it deploys;",
      `  - delete ${AASA_RELATIVE}, if this environment has no iOS client;`,
      `  - create ${AASA_SENTINEL_RELATIVE} to take manual ownership of the document`,
      "    for every environment (see public/.well-known/README.md).",
    );
  }

  if (present) {
    return {
      action: "keep",
      describe:
        `${AASA_RELATIVE} is hand-authored and ${AASA_SENTINEL_RELATIVE} claims it — ` +
        "leaving it exactly as committed",
    };
  }

  return {
    action: "none",
    describe: `Primitive environment "${env.name}" has no "iosAppId" and there is no ${AASA_RELATIVE} — nothing to serve`,
  };
}

/** Carries out a plan. `--check` never calls this. */
function applyAssociationDocument(plan) {
  if (plan.action === "write") {
    mkdirSync(dirname(plan.path), { recursive: true });
    writeFileSync(plan.path, plan.body);
  } else if (plan.action === "delete") {
    rmSync(plan.path, { force: true });
  }
}

/**
 * Every spelling of Wrangler's environment flag. Wrangler parses with yargs,
 * which accepts `-e alpha`, `-e=alpha` and `-ealpha` for the short form and
 * `--env alpha` / `--env=alpha` for the long one — and a later occurrence wins
 * over the `--env` this script passes. Matching only the exact tokens would
 * let `-e=alpha` through and deploy somewhere other than the environment the
 * run just printed, so every spelling of the flag itself is rejected. Longer
 * flags that merely begin with `--env` (`--env-file`) are left alone.
 */
const WRANGLER_ENV_FLAG = /^(--env(=.*)?|-e(=.*|.+)?)$/;

/** Rejects passthrough args that would take over what this script decides. */
function assertPassthroughIsSafe(passthrough) {
  for (let i = 0; i < passthrough.length; i++) {
    const arg = passthrough[i];
    if (WRANGLER_ENV_FLAG.test(arg)) {
      fail(
        `Passthrough argument "${arg}" would re-point the Wrangler environment.`,
        "Use --deploy-env, which sets both the Vite mode and the Wrangler environment.",
      );
    }
    const varValue = arg === "--var" ? passthrough[i + 1] : arg.startsWith("--var=") ? arg.slice("--var=".length) : null;
    if (varValue && /^(APP_ID|API_ORIGIN)[:=]/.test(varValue)) {
      fail(
        `Passthrough argument "--var ${varValue}" would override the identity this deploy resolved.`,
        "APP_ID and API_ORIGIN come from the Primitive environment; other --var flags pass through.",
      );
    }
  }
}

function runCommand(command, args, extraEnv = {}) {
  return new Promise((resolvePromise, reject) => {
    console.log(`\n> ${command} ${args.join(" ")}\n`);
    const child = spawn(command, args, {
      stdio: "inherit",
      shell: false,
      cwd: ROOT_DIR,
      env: { ...process.env, ...extraEnv },
    });
    child.on("close", (code) => {
      if (code === 0) resolvePromise();
      else reject(new Error(`Command failed with exit code ${code}`));
    });
    child.on("error", reject);
  });
}

async function main() {
  const args = parseArgs(process.argv.slice(2));

  if (args.positional !== null) {
    if (args.deployEnv !== null && args.deployEnv !== args.positional) {
      fail(
        `Conflicting deploy environments: "${args.positional}" (positional) and "${args.deployEnv}" (--deploy-env).`,
        "",
        USAGE,
      );
    }
    console.warn(
      `[deploy] Deprecated: the bare "${args.positional}" argument now means ` +
        `--deploy-env ${args.positional}. Pass it explicitly; it used to select the ` +
        `Primitive environment too, which is now --primitive-env.`,
    );
    args.deployEnv = args.positional;
  }

  if (!args.deployEnv || !args.primitiveEnv) {
    const missing = [
      !args.deployEnv ? "--deploy-env" : null,
      !args.primitiveEnv ? "--primitive-env" : null,
    ].filter(Boolean);
    fail(`Missing required option(s): ${missing.join(", ")}`, "", USAGE);
  }

  assertPassthroughIsSafe(args.passthrough);
  assertNoIdentityOverrides(args.deployEnv);
  assertPairing(args.deployEnv, args.primitiveEnv);

  const env = readPrimitiveEnvironment(args.primitiveEnv);
  // Decided before anything is printed or built: every refusal in here is a
  // wrong or stale association document, which fails silently once Apple has
  // cached it, so it stops a `--check` run exactly as it stops a real one.
  const association = planAssociationDocument(env, args.deployEnv);

  const buildArgs = ["build-only", "--mode", args.deployEnv];
  // `pnpm build` is `codegen && build-only`; a deploy runs `build-only` so it
  // can pass the mode explicitly, which used to skip the codegen entirely —
  // making the one build that SHIPS the one build compiling whatever generated
  // types happened to be in the tree (#3078). It runs with the same
  // environment as the build: the CLI codegen resolves PRIMITIVE_ENV, so a
  // codegen without it would emit workflow and database types from the
  // developer's local backend and ship them in the requested environment.
  const codegenArgs = ["codegen"];
  const buildEnv = { PRIMITIVE_ENV: env.name };
  const wranglerArgs = [
    "dlx",
    "wrangler",
    "deploy",
    "--env",
    args.deployEnv,
    "--var",
    `APP_ID:${env.appId}`,
    "--var",
    `API_ORIGIN:${env.apiUrl}`,
    ...args.passthrough,
  ];

  console.log("");
  console.log(`[deploy] Deploy environment:    ${args.deployEnv}  (Vite mode + wrangler [env.${args.deployEnv}])`);
  console.log(`[deploy] Primitive environment: ${env.name}`);
  console.log(`[deploy]   apiUrl:  ${env.apiUrl}`);
  console.log(`[deploy]   appId:   ${env.appId}`);
  console.log(`[deploy]   appName: ${env.appName ?? "(unset)"}`);
  console.log(`[deploy]   iosAppId: ${env.iosAppId ?? "(unset)"}`);
  console.log(`[deploy]   config:  ${env.configPath}`);
  console.log(`[deploy] Association: ${association.describe}.`);
  console.log("");

  if (args.check) {
    console.log("[deploy] --check: nothing will be built, written or deployed.");
    console.log(`[deploy] codegen:  pnpm ${codegenArgs.join(" ")}`);
    console.log(`[deploy] codegen env: PRIMITIVE_ENV=${buildEnv.PRIMITIVE_ENV}`);
    console.log(`[deploy] build:    pnpm ${buildArgs.join(" ")}`);
    console.log(`[deploy] build env: PRIMITIVE_ENV=${buildEnv.PRIMITIVE_ENV}`);
    console.log(`[deploy] deploy:   pnpm ${wranglerArgs.join(" ")}`);
    return;
  }

  // Before the build: Vite copies public/ into dist/ verbatim, and dist/ is
  // what wrangler serves.
  applyAssociationDocument(association);

  // Before the build, so the shipped bundle compiles the types this
  // environment's schemas describe — and so the regenerated output lands in the
  // working tree as a diff to commit, like every other build path.
  console.log(`[deploy] Regenerating from Primitive environment "${env.name}"...`);
  try {
    await runCommand("pnpm", codegenArgs, buildEnv);
  } catch (error) {
    fail(`Codegen failed: ${error.message}`);
  }

  console.log(`[deploy] Building for deploy environment "${args.deployEnv}"...`);
  try {
    await runCommand("pnpm", buildArgs, buildEnv);
  } catch (error) {
    fail(`Build failed: ${error.message}`);
  }

  console.log("\n[deploy] Deploying to Cloudflare Workers...");
  try {
    await runCommand("pnpm", wranglerArgs);
  } catch (error) {
    fail(`Deploy failed: ${error.message}`);
  }

  console.log("\n[deploy] Deployment complete!");
}

main().catch((error) => {
  console.error("[deploy] Unexpected error:", error);
  process.exit(1);
});
